# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The So Company
email: so@socompany.com
description: > # this means to ignore newlines until "baseurl:"
  A veteran-owned business committed to making government work better.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thesocompany.com" # the base hostname & protocol for your site
twitter_username: thesocompany
github_username:  thesocompany

# Build settings
markdown: kramdown
